language: cpp
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yq automake gtk-doc-tools
  - sudo apt-get install -yq gobject-introspection
  - sudo apt-get install -yq libfftw3-dev libjpeg-turbo8-dev
  - sudo apt-get install -yq libpng12-dev libwebp-dev libtiff4-dev libxml2-dev
  - sudo apt-get install -yq swig libmagick++-dev bc
  - sudo apt-get install -yq libcfitsio3-dev libgsl0-dev libmatio-dev
  - sudo apt-get install -yq liborc-0.4-dev liblcms2-dev libpoppler-glib-dev
  - sudo apt-get install -yq libpango1.0-dev libgsf-1-dev libopenslide-dev
  - sudo apt-get install -yq libgif-dev librsvg2-dev
  - sudo apt-get install -yq python-dev python-gi-dev libgirepository1.0-dev
before_script:
  - ./bootstrap.sh
  - ./configure --enable-pyvips8
  - make -j`nproc`
script:
  - cd test && GI_TYPELIB_PATH=../libvips LD_LIBRARY_PATH=../libvips/.libs /usr/bin/python -m unittest -v test_all
