language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      cache: ccache
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y
          automake gtk-doc-tools
          gobject-introspection
          libfftw3-dev libjpeg-turbo8-dev
          libpng12-dev libwebp-dev libtiff4-dev libxml2-dev
          swig libmagick++-dev bc
          libcfitsio3-dev libgsl0-dev libmatio-dev
          liborc-0.4-dev liblcms2-dev libpoppler-glib-dev
          libpango1.0-dev libgsf-1-dev libopenslide-dev
          libgif-dev librsvg2-dev libopenexr-dev
          python-dev
      before_script:
        - ./bootstrap.sh
        - ./configure
          --disable-dependency-tracking
        - make -j`nproc`
      script:
        - make check
    - os: linux
      sudo: required
      dist: trusty
      cache: ccache
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y
          automake gtk-doc-tools
          gobject-introspection
          libfftw3-dev libjpeg-turbo8-dev
          libpng12-dev libwebp-dev libtiff4-dev libxml2-dev
          swig libmagick++-dev bc
          libcfitsio3-dev libgsl0-dev libmatio-dev
          liborc-0.4-dev liblcms2-dev libpoppler-glib-dev
          libpango1.0-dev libgsf-1-dev libopenslide-dev
          libgif-dev librsvg2-dev libopenexr-dev
          python-dev python-gi-dev libgirepository1.0-dev
      before_script:
        - ./bootstrap.sh
        - ./configure
          --disable-dependency-tracking
          --enable-pyvips8
        - make -j`nproc`
      script:
        - make check
        - cd test &&
          GI_TYPELIB_PATH=../libvips
          LD_LIBRARY_PATH=../libvips/.libs
          /usr/bin/python -m unittest -v test_all
    - os: osx
      osx_image: xcode7.3
      cache:
        - ccache
        - directories:
          - /usr/local/Cellar/libxml2
      before_cache:
        - brew cleanup libxml2
      before_install:
        - brew update
        - brew install
          ccache pkg-config
          automake gtk-doc
          gobject-introspection
          fftw mozjpeg libexif
          libpng webp libtiff
          swig imagemagick
          cfitsio homebrew/science/libmatio
          orc little-cms2 poppler
          pango libgsf openslide
          giflib librsvg openexr
          python pygobject3
      before_script:
        - ./bootstrap.sh
        - PKG_CONFIG_PATH='/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pygobject3/lib/pkgconfig'
          ./configure
          --disable-dependency-tracking
          --with-jpeg-includes=/usr/local/opt/mozjpeg/include
          --with-jpeg-libraries=/usr/local/opt/mozjpeg/lib
          --enable-pyvips8
        - PATH="/usr/local/opt/ccache/libexec:$PATH" make -j`sysctl -n hw.ncpu`
      script:
        - make check
        - cd test &&
          GI_TYPELIB_PATH=../libvips
          DYLD_LIBRARY_PATH=../libvips/.libs
          /usr/local/bin/python -m unittest -v test_all
  allow_failures:
    - os: osx
  fast_finish: true
